name: confluence-publish-article
description: Copy content of a markdown file to a confluence site
runs:
  using: docker
  image: Dockerfile
inputs:
  from:
    description: Path to the markdown file
    required: true
  to:
    description: The page id in Confluence
    required: true
  cloud:
    description: Atlassian Cloud id
    required: true
  user:
    description: Username of the token user
    required: true
  token:
    description: Token for the user
    required: true
outputs:
  url:
    description: Url of the Confluence article
